# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: mickeygo blog
email: yanggangc@163.com
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://mickeygo.github.io" # the base hostname & protocol for your site, e.g. http://example.com
# twitter_username: jekyllrb
github_username:  mickeygo

# Build settings
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Build settings
# 语法高亮
#highlighter: pygments
# markdown解释器
#markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

#relative_permalinks: true
#博文的链接样式
permalink: /:year-:month-:day-:title.html

favicon: /assets/image/favicon.ico

# 博客作者相关
author:
  name: mickeygo
  email: yanggangc@163.com
  link: http://mickeygo.github.io/
  # weibo: ""
  # weibo_username: ""
  github: https://github.com/mickeygo
  github_username: mickeygo


locals:
  tags: 标签
  about: 关于
  active: 技术
subscribe_rss: /pages/atom.xml

# 头像
avatar: /assets/image/avatar.png
# avatar: http://7xpapo.com1.z0.glb.clouddn.com/blog/assets/image/favicon.ico
# 网站CSS路径
css: /assets/css/
# css: http://7xpapo.com1.z0.glb.clouddn.com/blog/assets/css/
# 网站JS路径
js: /assets/js/
# js: http://7xpapo.com1.z0.glb.clouddn.com/blog/assets/js/
# 网站图片路径
image: /assets/image/
# image: http://7xpapo.com1.z0.glb.clouddn.com/blog/assets/image/

# disqus 设置
disqus:
  shortname: mickeygo
